GET localhost:8080/api/stores

###
POST localhost:8080/api/stores/addStore
Content-Type: application/json

{
  "name": "Mcdonalds",
  "rent": "1200",
  "storekeeper": "Ronald Mcdonald",
  "category": "gastronomy"
}

###
POST localhost:8080/api/stores/addStores
Content-Type: application/json

[
  {
    "name": "Mcdonalds",
    "rent": "1200",
    "storekeeper": "Ronald Mcdonald",
    "category": "gastronomy"
  },
  {
    "name": "Mediamarkt",
    "rent": "350",
    "storekeeper": "Donald Duck",
    "category": "ELECTRONICS"
  }
]

###
DELETE localhost:8080/api/stores/delStore
Content-Type: application/json

{
  "id": 2
}

###
PATCH localhost:8080/api/stores/updateRent
Content-Type: application/json

{
  "name": "Mcdonalds",
  "newRent": "2500"
}

###
GET localhost:8080/api/stores/findStoreName?name=Mcdonalds

###
GET localhost:8080/api/stores/4
