openapi: 3.0.1
info:
  title: Static OpenAPI document of store resource
  description: Store resources Open API documentation
  version: "1.0"

servers:
  - url: http://localhost:8080/openapi
    description: Optional dev mode server description
paths:
  /stores/addStore:
    post:
      summary: Adds a new store
      requestBody:
        content:
          application/json:
            schema:      # Request body contents
              type: object
              properties:
                name:
                  type: string
                rent:
                  type: string
                storekeeper:
                  type: string
                category:
                  type: string
              example:   # Sample object
                name: "Mcdonalds"
                rent: "1200"
                storekeeper: "Ronald Mcdonald"
                category: "gastronomy"
      responses:
        '200':
          description: OK
