@startuml
left to right direction
User --> (Get all stores)
User --> (Find a Store with name or Id)
User --> (Add a Store)
User --> (Delete a Store)
User --> (Add Event)
User --> (Find a Event)
User --> (Delete a Event)
@enduml